# Generated by Django 4.0.4 on 2022-05-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_info',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
