# Generated by Django 4.0.4 on 2022-05-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_posts_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts_info',
            field=models.TextField(default='{}'),
        ),
    ]
