# Generated by Django 4.0.4 on 2022-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('article', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title_url', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=250)),
                ('content', models.TextField()),
                ('views', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
